### ISSUE TITLE
[Badge - oturotur]

### ISSUE THREAD

**Issue by aharshbe** [aharshbe/sdfsdfsdfsdfsdf#19]
dfdfgdfg

**Comment by aharshbe** [comment]
This issue does not qualify for a contributor badge because a bot is suspected. If you are not a bot, please reach out to us directly and provide proof.

**Comment by Sabbir847** [comment]
why close my contributors sir?

**Comment by aharshbe** [comment]
This issue does not qualify for a contributor badge because a bot is suspected. If you are not a bot, please reach out to us directly and provide proof.
